algoritmo "Estrutuas Condicionais"

var

//Declaração de variavel
N : inteiro

inicio

//Atribuição do valor 15 à variável N
N <- 1

//Verificando cada uma das condições.
escreval("N > 0: ", N > 0)      //Resultado: V (Verdadeiro)
escreval("N = 6: ", N = 6)      //Resultado: F (Falso)
escreval("N <= 50: ", N <= 50)  //Resultado: V (Verdadeiro)
escreval("N <> 12: ", N <> 12)  //Resultado: V (Verdadeiro)



fimalgoritmo