Algoritmo "EXERCICIO_MEDIDAS"

Var

A, B, C, area_quadrado, area_triangulo, area_trapezio : real


Inicio

escreva("Digite a medida A : ")
leia(A)
escreva("Digite a medida B : ")
leia(B)
escreva("Digite a medida C : ")
leia(C)

area_quadrado <- exp(A,2)
area_triangulo <- (A * B) / 2
area_trapezio <- ((A + B) * C) / 2

escreval("AREA DO QUADRADO = ",area_quadrado:6:4)
escreval("AREA DO TRIANGULO = ",area_triangulo:6:4)
escreval("AREA DO TRAPEZIO = ",area_trapezio:6:4)







Fimalgoritmo