Algoritmo "Exercicio_PAGAMENTO"

Var

nome: caractere
valor_por_hora, pagamento : real
horas_trabalhadas: inteiro



Inicio

escreva("Digite seu nome : ")
leia(nome)
escreva("Valor por hora : ")
leia(valor_por_hora)
escreva("Horas trabalhadas : ")
leia(horas_trabalhadas)

pagamento <- valor_por_hora * horas_trabalhadas

escreval("O pagamento para " ,nome, " deve ser",pagamento:8:2)






Fimalgoritmo